version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
      - whoami
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - pwd
  build:
    commands:
      - echo Build started on `date`
      - docker --version
  post_build:
    commands:
      - echo Build completed on `date`
      - which gauntlt