version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
      - whoami
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - pwd
      - arachni --version
  build:
    commands:
      - echo Build started on `date`
      - arachni --checks=xss --scope-directory-depth-limit=1 https://www.google.com 
  post_build:
    commands:
      - echo Build completed on `date`
      - which gauntlt